### ISSUE TITLE
Sales Manager - Sales Funnel

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-gallery#28]
Create a sales funnel using https://www.fusioncharts.com/charts/funnel-charts/.  A query is being developed for this for Epicor now with the following direction:

o	Return the current sales funnel in dollars.  I know Epicor has a concept within a quote for the various stages, will need to see if Visual has the same.  I will be presenting them in the order the query returns them so sort them according to process order.

Develop the initial version Excel targeted with a similar data profile in mind.

**Comment by aellis** [comment]
Note on this one - this goes under the role for sales manager and sales rep.  The query itself / BRDB permissions will control the data that comes back so just document when switching the connection that they should add a parameter with bezl.env.currentUser.

**Comment by bschnabs** [comment]
@OnlyAGhost @aellis do we have a query yet for this?

**Comment by aellis** [comment]
It doesn't look like we have got one yet.

**Comment by OnlyAGhost** [comment]
I could prob create a Salesforce one quick. Or mock it in Excel

Sent from my iPhone

On Nov 6, 2017, at 6:40 PM, Adam Ellis <notifications@github.com<mailto:notifications@github.com>> wrote:


It doesn't look like we have got one yet.

**Comment by bschnabs** [comment]
Yeah I'm just going to mock something up quick. Just wanted to check to avoid double work.

**Comment by aellis** [comment]
@soft-Dev - I just added this pull request.  Looks like we have a small tweak - can you set the default data source upon installation to be Excel?  It is set up to Epicor currently.  Also, go ahead and make this one a featured.  I think we will feature all new additions by default.
