### ISSUE TITLE
Shipping Worker - Picklist

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-gallery#35]
This will be for a digital picklist.  User should input a date range for the ship by date and it will return all of the items to ship.  When tapping on an entry, it should expand out and show the locations that inventory can currently be picked from.  Here is the query spec out for development:

o	Create a query to do a picklist.  Make a date range for the ship by date.  For each line also include the inventory locations.

**Comment by gramang** [comment]
@aellis  We have Updated query, please check and confirm
[PickList.txt](https://github.com/bezlio/bezlio-gallery/files/1491472/PickList.txt)

**Comment by OnlyAGhost** [comment]
[Digital Picklist.txt](https://github.com/bezlio/bezlio-gallery/files/1527707/Digital.Picklist.txt)

@NDMO @kmansfield I need to bug squash in webapp since portal is kind of buggy I would like to replace it out ASAP. The queries are already done, Nick can you add the date filter and then Kevin can you just make it look better?

**Comment by NDMO** [comment]
@OnlyAGhost @aellis When clicking on a part, if there is no warehouse associated with it, do you want the warehouse grid to display something? currently it is displaying nothing, could be seen as not working in the customer eyes. 
Also do you want a default query to run when the bezl is first started? or do you want it to require a date entry?

**Comment by OnlyAGhost** [comment]
@NDMO When it first opens run the query, we are pulling all the data in and filtering it in JS (since thats the only way to make it universal currently). Start with the current month of the filter.

**Comment by NDMO** [comment]
[Digital Picklist.txt](https://github.com/bezlio/bezlio-gallery/files/1531545/Digital.Picklist.txt)
Ready for that design work @kmansfield

**Comment by kmansfield** [comment]
@NDMO @OnlyAGhost @aellis 

Working on styling it now.

I love Nick's suggestion about setting it to display something in the supply column when clicking on a part and there is no warehouse associated with it.

We can also add a Bootstrap contextual class (primary, success, warning, etc.) to the table row on the demand side when it is clicked. This would change the color of the clicked row to the color of the contextual class. Note the dummy row I placed into this image:   

![table-rows](https://user-images.githubusercontent.com/33261564/33625071-6e910bd6-d9c4-11e7-8541-77dc1ddb047d.jpg)

This would help the user keep track of the item clicked and also reinforce the idea that it's working. Blue is the info class in Bootstrap that I used here. We could also do success and danger classes to show green if a part is available at a warehouse, and red if it's not.

Thoughts? If we wanted to work this out, I would want help with the js, cause I don't wanna go messing around these functions.

**Comment by OnlyAGhost** [comment]
I think all that looks great! Love adding that context in there

**Comment by kmansfield** [comment]
[Labor Entry.txt](https://github.com/bezlio/bezlio-gallery/files/1532841/Labor.Entry.txt)

@NDMO Here's that Bezl. I want to go with Bootstrap's active class for context, which is just gray. I left it in there for reference if you need it, so just delete that dummy row I added to the demand table when you're done.
