### ISSUE TITLE
Accounts View - Implement pagination

### ISSUE THREAD

**Issue by OnlyAGhost** [bezlio/bezlio-gallery#36]
The performance of accounts view on mobile devices leaves a lot to be desired. Implement a new version of accounts view that uses pagination to reduce the overall data load.

**Comment by kmansfield** [comment]
[proposed_account_view_mockups.pdf](https://github.com/bezlio/bezlio-gallery/files/1450878/proposed_account_view_mockups.pdf)

I attached a walk-through of a redesign. Let me know what you guys think.

**Comment by OnlyAGhost** [comment]
@kmansfield I copied you on the contact at Sunlight correct? would you like to get his input?

**Comment by kmansfield** [comment]
Yeah, that would be good. I had a couple ideas that I laid out. Any feedback is good. I also wanted to make sure this was what you had in mind regarding the pagination, navigation by alphabet, and other features we discussed


Kevin Mansfield

Web Designer

SaberLogic

________________________________

**Comment by NDMO** [comment]
@kmansfield let me know when you are finished up with the ui design, Then i can work on the bugs in the js

**Comment by NDMO** [comment]
note to self: js files will have to be modified:
       bezl.data.Accounts => bezl.vars.displayedAccounts....

**Comment by kmansfield** [comment]
Cool, I'll let you know when I'm done.


Kevin Mansfield

Web Designer

SaberLogic

________________________________
