### ISSUE TITLE
Production Worker - Issue Materials - Remove Materials Exist Validation (Customer Related)

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-gallery#48]
Adding this issue in gallery since this is now a gallery item, but this is a customer-originated request on paid services.  We have a validation in place on the issue materials Bezl that pops an alert if no materials exist on the selected job / ?asm / ?op.  Since this Bezl allows you to add materials on the fly, this validation no longer serves a purpose, so remove it.

**Comment by aellis** [comment]
Upon completion of this task, please connect with @aellis as we need to load this up into the requesting customers' account as well.

**Comment by OnlyAGhost** [comment]
Verified with Adam it should be removed permanently from the gallery.

**Comment by OnlyAGhost** [comment]
@NDMO can you work with @PriSaber for this request? Should be a good entry point to the process.

**Comment by PriSaber** [comment]
@aellis I updated code to remove the validation for materials and committed the code.

**Comment by aellis** [comment]
@PriSaber - great - thank you!  I will take care of getting this installed for the customer, so closing this issue out.
