### ISSUE TITLE
Job Schedule - Gantt Chart - Thumbnail Image Size Incorrect

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-gallery#51]
The thumbnail for Job Schedule - Gantt Chart is incorrectly sized and is throwing off the gallery.  Resize it to 1000x350.

**Comment by bschnabs** [comment]
This is in the pull request for the SSRS plugin.

**Comment by OnlyAGhost** [comment]
Verified this is correct now. Closing ticket.
